WoEN: ULT Into The Deep v0.0
WoEN239/IntoTheDeep17517 pull request #2
Opened 2024-10-16 17:12 UTC by EgorKhvostikov

v0.0

2024-10-21 11:34 UTC, oaleksander requested changes

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpenCv/myPipeLine.java
> +public class myPipeLine extends OpenCvPipeline {
Названия классов должны быть с большой буквы. Названия классов должны отражать их назначения - для чего этот `Pipeline`?

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpenCv/Camera.java
> +    public static int HEIGHT = 480;
Советую выбрать разрешение с соотношением сторон 16:9 (как у самой камеры)

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/State.java
> +public enum State {
Дать более конкретное название класса. `State` чего?

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/Grabber/TransferPosition.java
> +
Убрать отступ после аннотации

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/Grabber/GrabberUpPosition.java
> +public enum GrabberUpPosition {
Чем это отличается от просто `GrabberPosition?`

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +        double u = ((voltage / 12.0) * (12.0 / battery.getVoltage()));
12 в числителе и знаменателе сокращаются, можно убрать

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +    public FilterStatus filterStatus = new FilterStatus(6, 150, 30, 1, 0.1, 0.3);
Сделать параметры настраиваемыми через FTC Dashboard

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +    private int dir = 1;
Лучше использовать FTCшный класс `Direction` или свой `enum{FORWARD,REVERSE,NONE}` сделать

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/Filter.java
Хорошо бы вынести функции для обработки массивов (медиана, среднее, буфер со сдвигом элементов) в отдельный класс(ы)

Кстати про буфер. Советую на досуге почитать про циклические буферы

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/Filter.java
> +        double dt = tNow - tOld;
Лучше сбрасывать таймер (`ElapsedTime.reset()`). Если там набежит какое-то большое количество секунд, то при нахождении разницы между двумя большими числами с плавающей запятой может потеряться точность.

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/FilterStatus.java
> +    }
Это такой способ добавить галочку для параметра "по этому `FilterStatus` надо выводить телеметрию"? Выглядит, как зона ответственности другого класса

Можно написать отдельную прослойку для телеметрии, в которую добавить различные "Тематики" или уровни логирования

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/Position.java
> +    }
Добавить суммирование h или явно обозначить что его там не должно быть

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Controllers/VelocityController.java
> +        }
Надо ли здесь в явном виде останавливать моторы при `isUpdate == false`? Если его внезапно выключили при ненулевом питании моторов.

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Devices/Gyro.java
> +        speed = imu.getRobotAngularVelocity(AngleUnit.RADIANS).xRotationRate;
Там точно скорость вокруг `x` должна быть?

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +
Убрать пустую строку после аннотации

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +    public static double fieldVoltage = 3;
Добавить разные значения порога для разных датчиков. Возможно, дать более значащее значение переменной

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +
убрать лишний отступ

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +
Убрать лишний отступ

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +
Убрать лишний отступ

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/PositionViewer/PositionLocalViewer.java
> +
Убрать лишний отступ

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/FieldSensors/FieldSensors.java
> +            }
Уменьшить количество отступов, используя `else if` на одной строке

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/RoadRunner/RoadRunner.java
> +    public TrajectoryBuilder builder() {
Обратите внимание, что в `TrajectoryBuilder` нет метода для поворота. Но зато в RR есть класс `TimeTurn`, который позволяет делать повороты по аналогии с `TimeTrajectory`. Неплохо бы добавить возможность обрабатывать их в `move`.

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/RoadRunner/RobotConstant.java
> +    public static double MAX_RPM = 480;
у тетрикс мотора с 20-м редуктором максимальные обороты при 12В по паспорту - 300RPM

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/Grabber/Grabber.java
> +    private Servo transferServoFirst;
Дать более конкретные названия устройствам, например `Left`/`Right`

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/GrabberStateMachine.java
> +        if (isOn) {
Можно уменьшить вложенность, сделав
```java
if(!isOn){
    return;
}
```

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    }
Выглядит очень полезным классом, можно вынести в отдельный файл

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    public static TEAM myTEAM = TEAM.BLUE;
По стандарту переменнаые поля оформляются через `lowerCamelCase` - `myTeam`

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Devices/Gyro.java
Чтение гироскопа - очень дорогая операция, при чем сам BNO055 не умеет выдавать данные чаще 100 раз в секунду (вроде бы). Предлагаю искуственно занизить скорость опроса, сделав её намного ниже, скажем, 50 Гц или 25 Гц.

2024-10-21 11:34 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/GrabberAndTransferServo.java
> +    public Servo transferServoSecond;
Надо деть более конкретные названия устройствам. Не `First`/`Second`, а, скажем, `Left`/`Right`, явно указывающее на той, какой это сервопривод.

2024-10-22 14:30 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpenCv/Camera.java
> +    public static int HEIGHT = 480;
Сделано, на 800x448

2024-10-22 14:31 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpenCv/myPipeLine.java
> +public class myPipeLine extends OpenCvPipeline {
Переделано на SimplesAndTagsDetectPipeline

2024-10-22 14:33 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/State.java
> +public enum State {
Изменение на `IntakeState`

2024-10-22 14:33 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/Grabber/TransferPosition.java
> +
Убрано

2024-10-22 14:35 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/Intake/Grabber/GrabberUpPosition.java
> +public enum GrabberUpPosition {
Сейчас поменяю название на более правильное, но это для захвата ,работающего на подъем захвата прототипов.

2024-10-22 14:42 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    }
Вынес в отдельный enum `TEAM`

2024-10-22 14:43 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    public static TEAM myTEAM = TEAM.BLUE;
Исправлено на `myTeam`

2024-10-22 14:50 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/GrabberAndTransferServo.java
> +    public Servo transferServoSecond;
Я создал, второй сервопривод, потому что мне сказали, что не факт что он будет

2024-10-24 13:41 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +    public FilterStatus filterStatus = new FilterStatus(6, 150, 30, 1, 0.1, 0.3);
уже( там мотор статик, фильтер статус паблик, и через дэш всё настраивается)

2024-10-24 13:58 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/FilterStatus.java
> +    }
Это нужно чтобы не писать где-то addData(...) по много раз на мотор, в сейчас просто заходишь в дэш, ставишь галочку и всё нужное выводится, сама функция нужна, если в каком-то натсроичном OpMode всегда нужно выводить,  не ставить галочку после каждого перезалива

2024-10-24 14:01 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Controllers/VelocityController.java
> +        }
не нужно, суть как раз в том чтобы мочь выключить все setPower в каком-то из модулей, если есть несколько возможных мест выставления этих SetPowers

2024-10-24 14:02 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Devices/Gyro.java
> +        speed = imu.getRobotAngularVelocity(AngleUnit.RADIANS).xRotationRate;
Не знаю, как только появится робот - посмотрим какие настройки нужны для гиро

2024-10-26 10:42 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +    public FilterStatus filterStatus = new FilterStatus(6, 150, 30, 1, 0.1, 0.3);
Круто, не обратил внимания

2024-10-26 10:58 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/Devices/Gyro.java
> +        speed = imu.getRobotAngularVelocity(AngleUnit.RADIANS).xRotationRate;
Почти наверняка уверен, что там должна быть скоррость вокруг `z`. Обычно систему координат задают таким образом, что ось `z` смотрит вертикально, соответственно угол поворота это и есть угол вокруг вертикали.

2024-10-26 13:11 UTC, oaleksander requested changes

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/LiftHangingMotors.java
> +        liftRightMotor.dev.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
Очепятка, тут наверное должно быть `Left`/`Right`

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/MOTOR_DIRECTION.java
Отрефакторить название файла в `UpperCamelCase`

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +        double u = ((voltage ) * (battery.getVoltage()));
На напряжение батареи необходимо делить. Должно получиться, что чем больше перезаряд, тем меньший по факту `setPower` мы подаем

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +        this.battery = map.voltageSensor.get("Control Hub");
Необходимо сделать централизованный класс для считывания напряжения. В противном случае, каждый объект `Motor` будет отдельно пытаться считать напряжение каждый раз, хотя делать это чаще чем раз в цикл (а то и реже) не нужно.

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/Position.java
> +    }
Не нужно ли здесь сделать ограничение на h ∈ [-PI, PI] через специальную функцию?

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/PositionViewer/PositionViewer.java
> +        positionGlobal.plus(localViewer.deltaPosition);
Вот тут ошибочка с углом. 
`deltaPosition` содержит измение угла по энкодерам, но мы сначала берем с гироскопа `positionGlobal.h` = `robot.imu.getAngle();`, а потом к этому же `positionGlobal` прибавляем угол с одометров.
Кроме того, теперь на чтение гироскопа есть ограничение, поэтому угол с него будет отставать от реальности (но меньше накапливать ошибку).
Необхоидмо переписать определение угла:

1. Сначала посчитать глобальный угол по одометрам - просто разница энкодеров умноженная на какое-то число
2. Если есть новое(!!) измерение угла с гироскопа - скорректировать посчитанный в п.1 угол. Можно задействовать для этого экспоненциальный фильтр, но не обязательно.
3. Уже скорректированный угол использовать для поворота вектора и итоговой позиции

2024-10-26 13:11 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/PositionViewer/PositionLocalViewer.java
> +        double x = yOdometer.dev.getCurrentPosition();
Проблема: при вращении вокруг своей оcи на боковом одометре будет набегать какое-то значение, несмотря на то что робот вбок никуда не едет.
На передние одометры это не распространяется, поскольку они находятся на равном расстоянии от центра, и при повороте робота к ним прибавится/вычтется одинаковое значение, которое скомпенсируется при суммировании `(l + r) / 2.0`.
Что бы решить эту проблему, из бокового одометра надо вычесть значение, зависящее от угла (h). Его можно посчитать либо вручную (в зависимости от удаленности одометра от центра вращения), либо, ещё лучше, подобрать - проверните робота на какой-то известный угол и сосчитайте, сколько паразитных тиков набегает на боковом одометре.
P.S. устройство называется `yOdometer`, хотя ось названа `x`. Что бы себя не путать, надо сделать названия осей единообразным - в Dashboard/FTC SDK/Roadrunner используется СК, где `x` смотрит вперед, а `y` - налево (то есть на 90 гр. против ч.с. относительно `x`. Тогда названия энкодеров будут `xLeftOdometer`,`xRightOdometer`,`yOdometer`.

2024-10-26 13:24 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/LiftHangingMotors.java
> +        liftRightMotor.dev.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
Готово

2024-10-26 13:24 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/MOTOR_DIRECTION.java
Готово

2024-10-26 13:42 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +        this.battery = map.voltageSensor.get("Control Hub");
Сделали отдельный класс `Battery`

2024-10-26 14:07 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Math/Position.java
> +    }
Сделан ` while (abs(error)>180) error-=360*signum(error);
        return error;`

2024-10-26 14:20 UTC, MrFrosty1234 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Devices/Motor.java
> +        double u = ((voltage ) * (battery.getVoltage()));
Егор, сделал

2024-10-27 16:51 UTC, EgorKhvostikov commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Modules/DriveTrain/PositionViewer/PositionLocalViewer.java
> +        double x = yOdometer.dev.getCurrentPosition();
P.S. я ещё счёт скорости поправил. и кстати проблема с переполнение скорости одометром сама собой решилась, т.к. я сам скорость считаю на основе dr/dt, а позиция (тут r) не переполняется

2024-10-30 13:36 UTC, oaleksander submitted a review, later dismissed

2024-10-31 07:45 UTC, oaleksander approved these changes

2024-10-31 07:45 UTC, merged